### ISSUE TITLE
How To Run It?

### ISSUE THREAD

**Issue by zhenjiangma** [shivanshs9/explo19Cloud#1]
I download it ,but how to run it? I open it in IDEA, but I don't know how to run it. Could you help me?

**Comment by shivanshs9** [comment]
Installing the dependencies from pom.xml in the IDEA options. If you can't find option in IDE, then whip up the terminal and run `mvn install`. After that, run the static main from [AntColonyVMP](https://github.com/shivanshs9/acs-vm-migration/blob/master/src/main/java/com/faker/exploratory/ACO/AntColonyVMP.java)

**Comment by zhenjiangma** [comment]
Thanks! But there are still lots of errors reported. I want to to run it on the workload "PlanetLab 20110303", do you have a version on cloudsim not cloudsimPlus? I don't know if it is because of using cloudsim.

**Comment by shivanshs9** [comment]
Yes, the project requires Cloudsim Plus. It's explicitly mentioned as a dependency in **pom.xml** too.

**Comment by zhenjiangma** [comment]
Sad! I'm only familiar with cloudsim, so I have to give up your project.

**Comment by shivanshs9** [comment]
No problem! 👍

**Comment by shivanshs9** [comment]
Ah, that's sad. Anyways, I'm closing the issue then. 👍
